version: '3.4'
services:
  # These are backend services that the app depends on
  db:
    logging:
      driver: none
    image: postgres:13.4-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54320:5432"

  redis:
    image: redis:6.2.5-alpine
    command: redis-server
    logging:
      driver: none

  # These are the components of the app
  app:
    build:
      context: .
      args:
        UID: ${UID:-1001}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    entrypoint: ["bin/docker_start.sh"]

